### ISSUE TITLE
variable redefine error in iteration

### ISSUE THREAD

**Issue by happybean4** [Wopslang/Wops#48]
Once the iteration statement is rotated, the variable 'x' in the iteration statement must be removed from memory, but remains, generating an 'Redefine Error' for x.

Code
![image](https://user-images.githubusercontent.com/74172008/148645363-7883984b-f3a2-4566-8ee0-6af01d545273.png)

Output
![image](https://user-images.githubusercontent.com/74172008/148645375-9aa4fb06-0af2-44c7-b0b0-4baf7ff4621e.png)

**Comment by RedoC-github** [comment]
It seems a critical bug. Thanks for reporting.

**Comment by RedoC-github** [comment]
Sorry for the late reply.
We just checked the initialization system for in-block variables is missed, and we started to fix this error.

We'll contact you soon. Thank you

**Comment by RedoC-github** [comment]
#53

**Comment by RedoC-github** [comment]
Done!
